//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyRate {
    
    
    public partial class Default {
        
        /// <summary>
        /// FeaturedCarousel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AllRates.Modules.FeaturedCarousel FeaturedCarousel;
        
        /// <summary>
        /// NewsInBlog1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AllRates.Modules.HomeLoans.NewsInBlog NewsInBlog1;
        
        /// <summary>
        /// TodaysInterestRates control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AllRates.Modules.TodaysInterestRates TodaysInterestRates;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new EasyRate.Main Master {
            get {
                return ((EasyRate.Main)(base.Master));
            }
        }
    }
}
